### ISSUE TITLE
How to test this ?

### ISSUE THREAD

**Issue by akramraza2** [Istarnion/magic_touchscreen#1]
Clearly this use libevdev, but you have just provided the cpp files . How to include libevdev with this ?

**Comment by Istarnion** [comment]
The Makefile has the compiler invocation to link with libevdev and to point to the header files. I will modify README.md to include a note to install libevdev-dev, or the corresponding package for your distro.i
For a quick test, mark `magicts_test.cpp` as executable by running `chmod +x magicts_test.cpp` and run it. It will run make and compile the library, and then run a simple test program. You will of course need to install libevdev-dev first.
