### ISSUE TITLE
Running "make" returns Error 127

### ISSUE THREAD

**Issue by dastrobbel** [Istarnion/magic_touchscreen#3]
I'm new to Linux  and am working with Ubuntu 20.04.4LTS

I have installed `libevdev-dev` , `libc6` and `libevdev-doc` via `aptitude`.

When I move inside the terminal to `/magic-touchscreen-main` and run `make` it says:
`clang -shared -fPIC -I /usr/include/libevdev-1.0 src/magicts.ccp -o libmagicts.so -levdev
make: clang: Command not found
make: clang: *** [Makefile:11: libmagicts.so] Error 127`

**Comment by Istarnion** [comment]
You'll also need to intall the C++ compiler `clang`
You can do this by running `sudo apt install clang`

**Comment by dastrobbel** [comment]
Yes that's it
